port: 7880

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: true
  allow_tcp_fallback: true

turn:
  enabled: true
  domain: chat.bwondercomics.com
  udp_port: 443
  tls_port: 5349
  relay_range_start: 51000
  relay_range_end: 51100
  cert_file: /caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/chat.bwondercomics.com/chat.bwondercomics.com.crt
  key_file: /caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/chat.bwondercomics.com/chat.bwondercomics.com.key

redis:
  address: stoat-redis:6379

keys:
  lk_8f208e977e1778c6: c6400a89d0c8cc7c244bcc0d2a4b715534e7be2fcc2862acec4b43421167895e
